posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("create/", views.create_post, name="create_post"),
    path("delete/<int:post_id>/", views.delete_post, name="delete_post"),
]

the_social_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("", include("users.urls")),
    path("posts/", include("posts.urls")),
]

users/urls.py
from django.urls import path

from .views import signup_page, login_page, logout_page, profile_page, add_friend

app_name = "users"

urlpatterns = [
    path("signup/", signup_page, name="signup"),
    path("login/", login_page, name="login"),
    path("logout/", logout_page, name="logout"),
    path("<str:username>/", profile_page, name="profile"),
    path("friend/<int:pk>/", add_friend, name="add_friend"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from posts.models import Post, Comment


# Create your models here.
class User(AbstractUser):
    bio = models.TextField(blank=True)
    avatar = models.ImageField(upload_to="avatars", blank=True)
    location = models.CharField(max_length=100, blank=True)
    website = models.URLField(blank=True)
    birthdate = models.DateField(blank=True, null=True)
    friends = models.ManyToManyField("self", blank=True)
    # stats
    friendCount = models.IntegerField(default=0)
    postCount = models.IntegerField(default=0)
    commentCount = models.IntegerField(default=0)
    likeCount = models.IntegerField(default=0)
    profileViewCount = models.IntegerField(default=0)
    profileLikeCount = models.IntegerField(default=0)
    # settings
    isPrivate = models.BooleanField(default=False)
    isVerified = models.BooleanField(default=False)
    isSuspended = models.BooleanField(default=False)
    isDeleted = models.BooleanField(default=False)
    isBanned = models.BooleanField(default=False)

    def __str__(self):
        return self.username

    def create_friend_request(self, to_friend):
        friend_request, created = FriendRequest.objects.get_or_create(
            from_friend=self, to_friend=to_friend
        )
        return friend_request

    def remove_friend(self, to_friend):
        self.friends.remove(to_friend)
        to_friend.friends.remove(self)
        return None

    def get_friends(self):
        return self.friends.all()

    def get_friend_requests(self):
        return FriendRequest.objects.filter(to_friend=self)

    def get_friend_suggestions(self):
        # get 10 random users that are not friends with self
        return (
            User.objects.filter(friends__in=self.friends.all())
            .exclude(id__in=self.friends.values_list("id", flat=True))
            .exclude(id=self.id)
            .distinct()
        )

    def get_friend_suggestions_count(self):
        return (
            User.objects.filter(friends__in=self.friends.all())
            .exclude(id__in=self.friends.values_list("id", flat=True))
            .exclude(id=self.id)
            .distinct()
            .count()
        )

    def get_friend_count(self):
        return self.friends.all().count()

    def get_friends_posts(self):
        # get posts from friends and self

        return Post.objects.filter(
            author__in=self.friends.all() | User.objects.filter(pk=self.pk)
        ).order_by("-created_at")

    def get_own_posts(self):
        return Post.objects.filter(author=self).order_by("-created_at")


REQUEST_STATUS = (
    (0, "Pending"),
    (1, "Accepted"),
    (2, "Rejected"),
    (3, "Blocked"),
)


class FriendRequest(models.Model):
    from_friend = models.ForeignKey(
        User, related_name="friend_set", on_delete=models.CASCADE
    )
    to_friend = models.ForeignKey(
        User, related_name="to_friend_set", on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    status = models.IntegerField(choices=REQUEST_STATUS, default=0)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"{self.from_friend} follows {self.to_friend}"

    def accept(self):
        self.status = 1
        self.save()

        # create friendship from both sides
        self.from_friend.friends.add(self.to_friend)
        self.to_friend.friends.add(self.from_friend)

        # delete any reverse requests
        FriendRequest.objects.filter(
            from_friend=self.to_friend, to_friend=self.from_friend
        ).delete()

    def reject(self):
        self.status = 2
        self.save()

    def block(self):
        self.status = 3
        self.save()

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User


def signup_page(request):
    if request.method != "POST":
        return render(request, "users/signup.html")

    # POST
    username = request.POST["username"]
    # Check if username already exists
    if User.objects.filter(username=username).exists():
        return render(
            request, "users/signup.html", {"error": "Username already exists"}
        )

    password = request.POST["password"]
    password2 = request.POST["passwordConfirm"]
    if password != password2:
        return render(request, "users/signup.html", {"error": "Passwords don't match"})

    email = request.POST["email"]
    first_name = request.POST["firstName"]
    last_name = request.POST["lastName"]

    # Create user
    user = User.objects.create_user(username, email, password)
    user.first_name = first_name
    user.last_name = last_name
    user.save()

    login(request, user)
    return redirect("index")


def login_page(request):
    if request.method != "POST":
        return render(request, "users/login.html")

    # POST
    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)
    if user is None:
        return render(request, "users/login.html", {"error": "Invalid credentials"})

    login(request, user)
    return redirect("index")


def logout_page(request):
    logout(request)
    return render(request, "users/login.html", {"messages": ["Logged out!"]})


def profile_page(request, username):
    user = get_object_or_404(User, username=username)
    suggestions = request.user.get_friend_suggestions()[:5]
    context = {
        "user": user,
        "suggestions": suggestions,
    }
    if user == request.user:
        posts = user.get_friends_posts()
        context["posts"] = posts
        context["is_owner"] = True
    else:
        user.profileViewCount += 1
        user.save()
        context["is_owner"] = False
        context["posts"] = user.get_own_posts()

    return render(request, "users/profile.html", context)


def add_friend(request, pk):
    user = get_object_or_404(User, pk=pk)
    request.user.friends.add(user)
    return redirect("users:profile", username=user.username)

users/templates/users/_createPost.html
<div class="flex items-start space-x-4">
  <div class="min-w-0 flex-1">
    <form class="relative" method="POST" action="{% url 'posts:create_post' %}">
      {% csrf_token %}
      <div
        class="overflow-hidden rounded-lg shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600"
      >
        <label htmlFor="post" class="sr-only"> Share your story </label>
        <textarea
          rows="{3}"
          name="post"
          id="post"
          class="block w-full resize-none border-0 bg-transparent py-1.5 text-white placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"
          placeholder="Share your story..."
          defaultValue=""
        ></textarea>
        <!-- Spacer element to match the height of the toolbar  -->
        <div class="py-2" aria-hidden="true">
          <!-- Matches height of button in toolbar (1px border + 36px content
          height) -->
          <div class="py-px">
            <div class="h-9"></div>
          </div>
        </div>
      </div>

      <div class="absolute inset-x-0 bottom-0 flex justify-end py-2 pl-3 pr-2">
        <div class="flex-shrink-0">
          <button
            type="submit"
            class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Post
          </button>
        </div>
      </div>
    </form>
    {% if messages %} {% for message in messages %}
    <div
      class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative"
      role="alert"
    >
      <strong class="font-bold">Success!</strong>
      <span class="block sm:inline">{{ message }}</span>
    </div>
    {% endfor %} {% endif %}
  </div>
</div>

users/templates/users/_feed.html
<div class="flow-root">
  <ul role="list" class="-mb-8 divide-y divide-solid">
    {% for post in posts %}
    <li class="pt-8 first:pt-0">
      <div class="relative pb-8">
        <div class="relative flex items-start space-x-3">
          <div class="relative rounded-full bg-white">
            <!-- <UserCircleIcon
              class="flex h-10 w-10 items-center justify-center rounded-full"
            /> -->
          </div>
          <div class="min-w-0 flex-1">
            <div>
              <div class="flex justify-between items-center">
                <a
                  href="{% url 'users:profile' post.author.username %}"
                  class="font-medium text-white"
                >
                  {{ post.author.username }}
                </a>
                {% if post.author == request.user %}
                <a
                  class="text-sm text-red-500"
                  href="{% url 'posts:delete_post' post.id %}"
                  >DELETE</a
                >
                {% endif %}
              </div>
              <p class="mt-0.5 text-xs text-gray-500">
                Commented {{ post.created_at|timesince }} ago
              </p>
            </div>
            <div class="mt-2 text-sm text-gray-200">
              <p>{{post.body}}</p>
            </div>
          </div>
        </div>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>

users/templates/users/_friendSuggestions.html
<div class="rounded-lg bg-gray-50 shadow-sm ring-1 ring-gray-900/5 p-2">
  <h2 class="border-b border-gray-200 py-2 text-xl">People you may know</h2>
  <ul role="list" class="divide-y divide-gray-100">
    {% for user in suggestions %}
    <li class="relative flex justify-between gap-x-6 py-5">
      <div class="flex min-w-0 items-center gap-x-4">
        <!-- TODO: Add images -->
        <!-- <img
          class="h-12 w-12 flex-none rounded-full bg-gray-50"
          src="{user.imageUrl}"
          alt=""
        /> -->
        {% include 'icons/_userCircleIcon.html' %}
        <!-- <UserCircleIcon class="h-12 w-12" /> -->
        <div class="min-w-0 flex-auto">
          <p class="text-sm font-semibold leading-6 text-gray-900">
            <a href="{% url 'users:profile' user.username %}">
              <span class="absolute inset-x-0 -top-px bottom-0" />
              {{ user.username }}
            </a>
          </p>
          <p class="truncate">{{ user.get_full_name }}</p>
        </div>
      </div>
      <div class="flex shrink-0 items-center gap-x-4">
        <!-- <ChevronRightIcon
              class="h-5 w-5 flex-none text-gray-400"
              aria-hidden="true"
            /> -->
      </div>
    </li>
    {% endfor %}
  </ul>
</div>

users/templates/users/_navbar.html
{% load static %}
<header class="bg-gray-800">
  <div
    class="mx-auto max-w-7xl px-2 sm:px-4 lg:divide-y lg:divide-gray-700 lg:px-8"
  >
    <div class="relative flex h-16 justify-between">
      <div class="relative z-10 flex px-2 lg:px-0">
        <div class="flex flex-shrink-0 items-center">
          <img
            class="h-8 w-auto"
            src="{% static 'images/Logo.png' %}"
            alt="The Social App"
          />
        </div>
      </div>
      <div
        class="relative z-0 flex flex-1 items-center justify-center px-2 sm:absolute sm:inset-0"
      >
        <div class="w-full sm:max-w-xs">
          <label for="search" class="sr-only">Search</label>
          <div class="relative">
            <div
              class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3"
            >
              <svg
                class="h-5 w-5 text-gray-400"
                viewBox="0 0 20 20"
                fill="currentColor"
                aria-hidden="true"
              >
                <path
                  fill-rule="evenodd"
                  d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z"
                  clip-rule="evenodd"
                />
              </svg>
            </div>
            <input
              id="search"
              name="search"
              disabled
              class="block w-full rounded-md border-0 bg-gray-700 py-1.5 pl-10 pr-3 text-gray-300 placeholder:text-gray-400 focus:bg-white focus:text-gray-900 focus:ring-0 focus:placeholder:text-gray-500 sm:text-sm sm:leading-6 disabled:cursor-not-allowed"
              placeholder="Search"
              type="search"
            />
          </div>
        </div>
      </div>
      <div class="hidden lg:relative lg:z-10 lg:ml-4 lg:flex lg:items-center">
        <button
          type="button"
          disabled
          class="relative flex-shrink-0 rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 disabled:cursor-not-allowed"
        >
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">View notifications</span>
          <svg
            class="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"
            />
          </svg>
        </button>
      </div>
    </div>
    <nav class="hidden lg:flex lg:space-x-8 lg:py-2" aria-label="Global">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a
        href="{% url 'index' %}"
        class="bg-gray-900 text-white inline-flex items-center rounded-md py-2 px-3 text-sm font-medium"
        aria-current="page"
        >Home</a
      >
      <button
        href="#"
        disabled
        class="text-gray-300 hover:bg-gray-700 hover:text-white inline-flex items-center rounded-md py-2 px-3 text-sm font-medium disabled:cursor-not-allowed disabled:hover:bg-transparent disabled:hover:text-gray-300"
      >
        Friends
      </button>
      <button
        href="#"
        disabled
        class="text-gray-300 hover:bg-gray-700 hover:text-white inline-flex items-center rounded-md py-2 px-3 text-sm font-medium disabled:cursor-not-allowed disabled:hover:bg-transparent disabled:hover:text-gray-300"
      >
        Friend Request
      </button>
      <button
        href="#"
        disabled
        class="text-gray-300 hover:bg-gray-700 hover:text-white inline-flex items-center rounded-md py-2 px-3 text-sm font-medium disabled:cursor-not-allowed disabled:hover:bg-transparent disabled:hover:text-gray-300"
      >
        Settings
      </button>
      {% if request.user.is_authenticated %}
      <a
        href="{% url 'users:logout' %}"
        class="text-gray-300 hover:bg-gray-700 hover:text-white inline-flex items-center rounded-md py-2 px-3 text-sm font-medium"
        aria-current="page"
        >Logout</a
      >
      {% endif %}
    </nav>
  </div>
</header>

users/templates/users/_statLine.html
<div className="mt-4 flex w-full flex-none gap-x-4 px-6">
    <dt className="flex-none">
      <span className="sr-only">{label}</span>
      <Icon
        title={label}
        className="h-6 w-5 text-gray-400"
        aria-hidden="true"
      />
    </dt>
    <dd className="text-sm leading-6 text-gray-500">{value}</dd>
  </div>

users/templates/users/login.html
{% extends '_base.html' %} {% load static %} {% block content %}
<main class="bg-white mx-auto w-full md:w-3/5 mt-8 rounded-xl shadow-lg">
  <div
    class="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8"
  >
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <img
        class="mx-auto h-16 w-auto"
        src="{% static 'images/Logo.png' %}"
        alt="Your Company"
        width="40"
        height="40"
      />
      <h2
        class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900"
      >
        Create your new account
      </h2>
    </div>

    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
      <form class="space-y-6" action="{% url 'users:login' %}" method="POST">
        {% csrf_token %} {% if error %}
        <div
          class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"
          role="alert"
        >
          <strong class="font-bold">Oops!</strong>
          <span class="block sm:inline">{{ error }}</span>
          <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg
              class="fill-current h-6 w-6 text-red-500"
              role="button"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
            >
              <title>Close</title>
              <path
                d="M14.348 14.849a1 1 0 0 1-1.414 0L10
                    11.414l-2.93 2.93a1 1 0 1 1-1.414-1.414l2.93-2.93-2.93-2.93a1
                    1 0 1 1 1.414-1.414l2.93 2.93 2.93-2.93a1 1 0 1
                    1 1.414 1.414l-2.93 2.93 2.93 2.93a1 1 0 0
                    1 0 1.414z"
              />
            </svg>
          </span>
        </div>
        {% endif %} {% if messages %} {% for message in messages %}
        <div
          class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative"
          role="alert"
        >
          <strong class="font-bold">Success!</strong>
          <span class="block sm:inline">{{ message }}</span>
          <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg
              class="fill-current h-6 w-6 text-green-500"
              role="button"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
            >
              <title>Close</title>
              <path
                d="M14.348 14.849a1 1 0 0 1-1.414 0L10
                    11.414l-2.93 2.93a1 1 0 1 1-1.414-1.414l2.93-2.93-2.93-2.93a1
                    1 0 1 1 1.414-1.414l2.93 2.93 2.93-2.93a1 1 0 1
                    1 1.414 1.414l-2.93 2.93 2.93 2.93a1 1 0 0
                    1 0 1.414z"
              />
            </svg>
          </span>
        </div>
        {% endfor %} {% endif %}

        <div>
          <label
            for="username"
            class="block text-sm font-medium leading-6 text-gray-900"
          >
            Username
          </label>
          <div class="mt-2">
            <input
              id="username"
              name="username"
              type="text"
              autocomplete="username"
              required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            />
          </div>
        </div>

        <div>
          <div class="flex items-center justify-between">
            <label
              for="password"
              class="block text-sm font-medium leading-6 text-gray-900"
            >
              Password
            </label>
          </div>
          <div class="mt-2">
            <input
              id="password"
              name="password"
              type="password"
              autocomplete="current-password"
              required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            />
          </div>
        </div>

        <div>
          <button
            type="submit"
            class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Log in
          </button>
        </div>
      </form>

      <p class="mt-10 text-center text-sm text-gray-500">
        Need an account?
        <a
          href="{% url 'users:signup' %}"
          class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500"
        >
          Create one!
        </a>
      </p>
    </div>
  </div>
</main>

{% endblock content %}

users/templates/users/signup.html
{% extends '_base.html' %} {% load static %} {% block content %}
<main class="bg-white mx-auto w-full md:w-3/5 mt-8 rounded-xl shadow-lg">
  <div
    class="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8"
  >
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <img
        class="mx-auto h-16 w-auto"
        src="{% static 'images/Logo.png' %}"
        alt="Your Company"
        width="40"
        height="40"
      />
      <h2
        class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900"
      >
        Create your new account
      </h2>
    </div>

    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
      <form class="space-y-6" action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %} {% if error %}
        <div
          class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"
          role="alert"
        >
          <strong class="font-bold">Oops!</strong>
          <span class="block sm:inline">{{ error }}</span>
          <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg
              class="fill-current h-6 w-6 text-red-500"
              role="button"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
            >
              <title>Close</title>
              <path
                d="M14.348 14.849a1 1 0 0 1-1.414 0L10
                    11.414l-2.93 2.93a1 1 0 1 1-1.414-1.414l2.93-2.93-2.93-2.93a1
                    1 0 1 1 1.414-1.414l2.93 2.93 2.93-2.93a1 1 0 1
                    1 1.414 1.414l-2.93 2.93 2.93 2.93a1 1 0 0
                    1 0 1.414z"
              />
            </svg>
          </span>
        </div>
        {% endif %} {% if messages %} {% for message in messages %}
        <div
          class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative"
          role="alert"
        >
          <strong class="font-bold">Success!</strong>
          <span class="block sm:inline">{{ message }}</span>
          <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg
              class="fill-current h-6 w-6 text-green-500"
              role="button"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
            >
              <title>Close</title>
              <path
                d="M14.348 14.849a1 1 0 0 1-1.414 0L10
                    11.414l-2.93 2.93a1 1 0 1 1-1.414-1.414l2.93-2.93-2.93-2.93a1
                    1 0 1 1 1.414-1.414l2.93 2.93 2.93-2.93a1 1 0 1
                    1 1.414 1.414l-2.93 2.93 2.93 2.93a1 1 0 0
                    1 0 1.414z"
              />
            </svg>
          </span>
        </div>
        {% endfor %} {% endif %}
        <div>
          <label
            for="firstName"
            class="block text-sm font-medium leading-6 text-gray-900"
          >
            First Name
          </label>
          <div class="mt-2">
            <input
              id="firstName"
              name="firstName"
              type="text"
              autocomplete="firstName"
              required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            />
          </div>
        </div>
        <div>
          <label
            for="lastName"
            class="block text-sm font-medium leading-6 text-gray-900"
          >
            Last Name
          </label>
          <div class="mt-2">
            <input
              id="lastName"
              name="lastName"
              type="text"
              autocomplete="lastName"
              required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            />
          </div>
        </div>
        <div>
          <label
            for="username"
            class="block text-sm font-medium leading-6 text-gray-900"
          >
            Username
          </label>
          <div class="mt-2">
            <input
              id="username"
              name="username"
              type="text"
              autocomplete="username"
              required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            />
          </div>
        </div>
        <div>
          <label
            for="email"
            class="block text-sm font-medium leading-6 text-gray-900"
          >
            Email address
          </label>
          <div class="mt-2">
            <input
              id="email"
              name="email"
              type="email"
              autocomplete="email"
              required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            />
          </div>
        </div>

        <div>
          <div class="flex items-center justify-between">
            <label
              for="password"
              class="block text-sm font-medium leading-6 text-gray-900"
            >
              Password
            </label>
          </div>
          <div class="mt-2">
            <input
              id="password"
              name="password"
              type="password"
              autocomplete="current-password"
              required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            />
          </div>
        </div>
        <div>
          <div class="flex items-center justify-between">
            <label
              for="passwordConfirm"
              class="block text-sm font-medium leading-6 text-gray-900"
            >
              Confirm Password
            </label>
          </div>
          <div class="mt-2">
            <input
              id="passwordConfirm"
              name="passwordConfirm"
              type="password"
              autocomplete="password-confirmation"
              required
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            />
          </div>
        </div>

        <div>
          <button
            type="submit"
            class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Sign Up
          </button>
        </div>
      </form>

      <p class="mt-10 text-center text-sm text-gray-500">
        Already have an account?
        <a
          href="{% url 'users:login' %}"
          class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500"
        >
          Log In
        </a>
      </p>
    </div>
  </div>
</main>

{% endblock content %}